### ISSUE TITLE
Choose vue 3 UI framework

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/sidebase#2]
### Goal

List vue 3 ui component frameworks.

### Context

We may want to switch away from ant-design-vue. For this we should list and evaluate existing CSS frameworks. The comparison in the end should be similar to this one ORM comparison we did: https://github.com/sidestream-tech/shift-book/issues/49#issuecomment-1152344039

### Tasks

- [ ] list  shortcomings of ant-design vue
- [ ] List _answerable and understandable_ requirements in a first comment
  - answerable means: you should be able to give clear yes / no / number answers in a short form
  - understandable means: people with a base of web-development can read and understand them in a couple of words
  - see #1 for some requirements already gathered
- [ ] discuss requirements with @BracketJohn 
- [ ] Then create a table overview of exisitng frameworks that support vue3 
  - [ ] rate them in the requirements you listed above

**Comment by ManUtopiK** [comment]
Hi! Sidebase looks great. Awesome!

I don't know the scope of Sidebase and also this issue, if it's related to a CSS framework or UI framework.
Just I suggest considering also those UI frameworks :
- https://www.naiveui.com
- https://oruga.io

**Comment by BracketJohn** [comment]
Definitely related to UI - I've clarified this in the issue title.

> Hi! Sidebase looks great. Awesome!

Thanks @ManUtopiK, we appreaciate the feedback, feel free to give more and to recommend sidebase to others ❤️

**Comment by zoey-kaiser** [comment]
Hi @ManUtopiK thanks for the suggestions 🤗!

> * https://www.naiveui.com

I am pretty impressed by this framework. While the design patterns do remind me a bit of AntDesign, it has a few components that are very unique. I think it does make sense to include it in our discussion! We might also be able to offer multiple versions of sidebase, each with a separate framework, allowing developers to choose their favourite. 

> * https://oruga.io

What I really like about this framework is its ability to be modified with the help of TailwindCSS. While this is theoretically possible with most frameworks, I enjoy how they feature it on their [documentation site](https://oruga.io/documentation/#differences-between-default-and-full-css), leading me to believe that their components are written in such a way that there is minor collision with Tailwind styles (which we do have in other frameworks).

**Comment by BracketJohn** [comment]
Brief update: I think the general direction here is rather to build a small CLI where the users can select certain options they want to se5trup the project with.

One question could then be: What CSS UI framework do you want to use? A, B or C?

**Comment by ineshbose** [comment]
Been following this issue/project for a few weeks now - this is fantastic, and also a project extremely close to my interest!

As far as a component library goes, I've adopted PrimeVue personally because of the options and research I did seeing plenty others using it as well; I am currently in the process of trying to integrate it with Tailwind. This is after requiring to migrate a Vue 2 project using BootstrapVue (which is not very active atm) to Nuxt 3.

But a CLI would be very good option since it gives customisation to other users and instead of specialising in providing compatibility for only one library, it optimises for multiple. I believe a setup wizard similar `create-nuxt-app` would not return for Nuxt 3 which rather uses `nuxi`, so this can be a great way to setup projects. Happy to contribute where I can!

**Comment by BracketJohn** [comment]
Awesome! I agree that a CLI would be great at this point. From crunching through the `nuxt/framework` repo it looks like @atinux et al. don't have a large focus on this at the moment, so I think it's fair to start.

We have #13 for the cli, @zoey-kaiser is starting on a PoC of it at the moment (:

**Comment by ManUtopiK** [comment]
Hey!
Do you like tailwindcss ? Or even better : [unocss](https://github.com/unocss/unocss) ?
Do you know about [vueuse](https://vueuse.org/) ?
There is now a UI framework that use both of this excellent libraries !
It's very new, but looks awesome https://anu-vue.netlify.app

**Comment by BracketJohn** [comment]
Thanks for the suggestions!

Let's collect ideas here: https://github.com/sidestream-tech/sidebase/issues/13#issuecomment-1260530416

**Comment by BracketJohn** [comment]
for now we've settled on naive ui, checkout #80 to follow implementation progress.
